image: node:10

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

stages:
  - test
  - deploy

test:
  stage: test
  script:
    - yarn run lint
    - yarn run flow

deploy:
  stage: deploy
  only:
    - tags
  script:
    - echo "//registry.npmjs.org/:_authToken=${K8S_SECRET_NPM_TOKEN}" > ~/.npmrc
    - git config --global user.email "dev@zombee.dev"
    - git config --global user.name "dev"
    - yarn publish --non-interactive --access restricted --new-version=$CI_COMMIT_TAG
